# Generated by Django 4.0.5 on 2022-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato')], max_length=4)),
                ('idade', models.DateField()),
                ('vacinado', models.BooleanField(choices=[('Vacinado', True), ('Não vacinado', False)], default=False)),
                ('adotado', models.BooleanField(choices=[('Adotado', True), ('Não adotado', False)], default=False)),
            ],
        ),
    ]
