# Generated by Django 4.0.5 on 2022-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEPets', '0002_alter_pet_vacinado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adotado',
            field=models.BooleanField(choices=[(True, 'Adotado'), (False, 'Não adotado')], default=False),
        ),
    ]
